// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxsAA-zX_skK-JmNyiqTN19DEFJGbFK8Y',
    appId: '1:32797186943:web:dead5e449aa9630ccfd84a',
    messagingSenderId: '32797186943',
    projectId: 'asu-car-pool',
    authDomain: 'asu-car-pool.firebaseapp.com',
    storageBucket: 'asu-car-pool.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtbplptsLnuiBya3xj074D-fO6Pue9ZUM',
    appId: '1:32797186943:android:2a53c0a8f45a3695cfd84a',
    messagingSenderId: '32797186943',
    projectId: 'asu-car-pool',
    storageBucket: 'asu-car-pool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDppSulGco9-aBczJFRXgRVytZwAkhkIH0',
    appId: '1:32797186943:ios:7009d053de51ac0bcfd84a',
    messagingSenderId: '32797186943',
    projectId: 'asu-car-pool',
    storageBucket: 'asu-car-pool.appspot.com',
    iosBundleId: 'com.example.asuCarpool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDppSulGco9-aBczJFRXgRVytZwAkhkIH0',
    appId: '1:32797186943:ios:d99adee7bb3887f0cfd84a',
    messagingSenderId: '32797186943',
    projectId: 'asu-car-pool',
    storageBucket: 'asu-car-pool.appspot.com',
    iosBundleId: 'com.example.asuCarpool.RunnerTests',
  );
}
